---
- hosts: shardnofail:shardfail
  remote_user: "{{ ansible_user }}"
  vars:
    ansible_python_interpreter: '/usr/bin/python3'
  tasks:
    - name: Copying over config
      copy:
        src: sharddb.conf
        dest: /data/sharddb.conf
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
    
    - name: Ensuring existing data dirs
      state:
        path: "/data/shard"
      register: stats
    
    - name: Creating non-existing dirs
      file:
        path: "{{ item.item }}"
        state: directory
        mode: 0777
        group: "{{ ansible_user }}"
        owner: "{{ ansible_user }}"
      when: item.stat.exists == false
      with_items:
      - "{{ stats.results }}"
